using MillenniumWebFixed.Models;

public class Frames : IGeneralProjectDataBound
{
    public int? Id { get; set; }
    public int? GeneralProjectDataId { get; set; }
        public string NAME { get; set; }
        public string LABEL { get; set; }
        public int? PLIES { get; set; }
        public string FAMILY { get; set; }
        public string TYPE { get; set; }
        public double? SPAN { get; set; }
        public double? PITCH { get; set; }
        public double? CENTER { get; set; }
        public double? WEIGHT { get; set; }
        public double? VOLUME_ACTUAL { get; set; }
        public double? VOLUME_ACTUAL_SINGLE { get; set; }
        public double? VOLUME_STOCK { get; set; }
        public double? VOLUME_STOCK_SINGLE { get; set; }
        public double? CONNECTOR_AREA { get; set; }
        public double? CONNECTOR_AREA_SINGLE { get; set; }
        public int? CONNECTOR_POINTS { get; set; }
        public int? SPLICES { get; set; }
        public double? PRICE_PCS { get; set; }
        public int? TOTAL_PARTS { get; set; }
        public int? PARTS { get; set; }
        public string PRODUCTION_CASE { get; set; }
        public string FRAMING_ZONE { get; set; }
        public int? PRODUCTION_SET { get; set; }
        public string STOREY { get; set; }
        public string LAYOUT { get; set; }
        public string QUOTE_GROUP { get; set; }
        public double? OVERALL_SPAN { get; set; }
        public double? OVERALL_HEIGHT { get; set; }
        public int? ROOF_SEGMENTS { get; set; }
        public int? CEILING_SEGMENTS { get; set; }
        public string MATCH_GROUP { get; set; }
        public string MATCH_GROUP_MASTER { get; set; }
        public double? PRESS_SETUP_TIME { get; set; }
        public double? PRESSING_TIME { get; set; }
        public bool? IS_ATTIC { get; set; }
        public bool? IS_ON_CONCRETE { get; set; }
        public bool? HAS_LEFT_STUB { get; set; }
        public bool? HAS_RIGHT_STUB { get; set; }
        public int? NBR_OF_SUPPORTS { get; set; }
        public double? OVERHANG_FROM { get; set; }
        public double? OVERHANG_TO { get; set; }
        public double? TRANSPORTATION_LENGTH { get; set; }
        public double? TRANSPORTATION_HEIGHT { get; set; }
        public string PART_TRANSPORTATION_SIZES { get; set; }
        public string WINDOW_AREA { get; set; }
        public string DOOR_AREA { get; set; }
        public string PANEL_AREA { get; set; }
        public string WALL_PANEL_ASSEMBLY_TIME { get; set; }
        public double? SAW_SETUP_TIME { get; set; }
        public double? SAW_CUTTING_TIME_INSTANCE { get; set; }
        public string ROOM_WIDTH { get; set; }
        public string ROOM_HEIGHT { get; set; }
        public int? QUANTITY_SINGLE_PLY { get; set; }
        public int? FAMILY_ID { get; set; }
        public int? TYPE_ID { get; set; }
        public double? PITCH_TCL { get; set; }
        public string PITCH_TCR { get; set; }
        public int? PRESS_COUNT { get; set; }
        public int? TIMBER_COUNT { get; set; }
        public int? REDUCTIONS { get; set; }
        public int? HOUSINGS { get; set; }
        public int? HOLES { get; set; }
        public string CASSETTE { get; set; }
}