using MillinniumWebFixed.Models;

public class Generaldata : IGeneralProjectDataBound
{
    public int? Id { get; set; }
    public int? GeneralProjectDataId { get; set; }
        public string DESIGNER { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string PROJECT_NAME { get; set; }
        public string FABRICATOR { get; set; }
        public string TEMPLATE { get; set; }
        public string PROJECT_TYPE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string FINAL_CUSTOMER { get; set; }
        public string SITE_LOCATION { get; set; }
        public string SITE_ADDRESS { get; set; }
        public string ORDER_NUMBER { get; set; }
        public string DECLARATION_OF_PERFORMANCE { get; set; }
        public string PRODUCTION_CERTIFICATE_NO { get; set; }
        public string PRODUCTION_NOTIFICATION_NO { get; set; }
        public bool? SNOW_FENCE_IN_PROJECT { get; set; }
        public bool? TRANSPORT_SPLIT_FRAME_IN_PROJECT { get; set; }
        public bool? MEMBER_LAYER_CONNECTION_IN_PROJECT { get; set; }
        public bool? PLY_FRAMES_IN_PROJECT { get; set; }
        public bool? WEB_DESIGN_BRACE_IN_PROJECT { get; set; }
        public bool? SNOW_POCKETS { get; set; }
        public double? REFERENCE_WIND_SPEED { get; set; }
        public double? LAYOUT_FRAME_SPACING { get; set; }
        public double? BRACING_SPACING { get; set; }
        public double? PAMIR_VAT { get; set; }
        public double? EAVE_LINE { get; set; }
        public double? GABLE_LINE { get; set; }
        public double? RIDGE_LINE { get; set; }
        public double? HIP_LINE { get; set; }
        public double? VALLEY_LINE { get; set; }
        public double? MANSARD_LINE { get; set; }
        public double? POLYNESIAN_LINE { get; set; }
        public double? GABLE_AGAINST_WALL_LINE { get; set; }
        public double? MONO_HIGH_END_OVERHANG_LINE { get; set; }
        public double? TOTAL_WORKED_TIME { get; set; }
        public double? ROOF_SURFACE_AREA { get; set; }
        public double? ROOF_SURFACE_OUTSIDE_WALL_AREA { get; set; }
        public double? CEILING_SURFACE_AREA { get; set; }
        public double? FLOOR_SURFACE_AREA { get; set; }
        public double? ATTIC_ROOM_AREA { get; set; }
        public double? ATTIC_ROOM_LIVING_AREA { get; set; }
        public double? ATTIC_ROOM_AREA_ABOVE_1800 { get; set; }
        public string CUSTOMER_DATA_PATH { get; set; }
        public string DESIGN_CODE_LONG { get; set; }
        public string DESIGN_CODE_SHORT { get; set; }
        public double? DEAD_LOAD_ROOF { get; set; }
        public double? DEAD_LOAD_CEILING { get; set; }
        public double? DEAD_LOAD_CEILING_EXPOSED { get; set; }
        public double? DEAD_LOAD_WALL { get; set; }
        public double? DEAD_LOAD_ATTIC_FLOOR { get; set; }
        public double? DEAD_LOAD_ATTIC_ROOM_VERTICAL { get; set; }
        public double? DEAD_LOAD_ATTIC_CEILING { get; set; }
        public double? DEAD_LOAD_ATTIC_SLOPING_CEILING { get; set; }
        public double? DEAD_LOAD_OVERHANG_UNDERSIDE { get; set; }
        public double? LIVE_LOAD_1 { get; set; }
        public double? LIVE_LOAD_2 { get; set; }
        public double? LIVE_LOAD_3 { get; set; }
        public double? LIVE_LOAD_4 { get; set; }
        public double? LIVE_LOAD_ATTIC_PARTITION { get; set; }
        public double? LIVE_LOAD_ATTIC { get; set; }
        public double? PLATING_TOLERANCE { get; set; }
        public int? SNOW_LOAD { get; set; }
        public double? WIND_LOAD { get; set; }
        public double? TANK_LOAD { get; set; }
        public double? HOIST_LOAD { get; set; }
        public double? ALTITUDE { get; set; }
        public double? PITCH { get; set; }
        public double? FRAME_SPACING { get; set; }
        public string HEEL_TYPE { get; set; }
        public string VERTICAL_HEEL_OFFSET { get; set; }
        public string VERTICAL_HEEL_VERTICAL_HEIGHT { get; set; }
        public string STANDARD_HEEL_OVERHANG { get; set; }
        public string STANDARD_HEEL_PERPENDICULAR_HEIGHT { get; set; }
        public string PERPENDICULAR_HEEL_OFFSET { get; set; }
        public string PERPENDICULAR_HEEL_PERPENDICULAR_HEIGHT { get; set; }
        public string EXTENDEDBOTTOMCHORD_HEEL_OFFSET { get; set; }
        public string EXTENDEDBOTTOMCHORD_VERTICAL_HEIGHT { get; set; }
        public string FRAME_LABELS { get; set; }
        public double? TRANSPORTATION_LENGTH { get; set; }
        public double? TRANSPORTATION_HEIGHT { get; set; }
        public double? WALL_PLATE_WIDTH { get; set; }
        public double? WALL_PLATE_LAYBACK_FROM_OUTSIDE { get; set; }
        public string SERVICE_CLASS { get; set; }
        public string BUILDING_CATEGORY { get; set; }
        public string SNOW_ZONE { get; set; }
        public string CUSTOM_TEXT_1 { get; set; }
        public string CUSTOM_TEXT_2 { get; set; }
        public string CUSTOM_TEXT_3 { get; set; }
        public string CUSTOM_TEXT_4 { get; set; }
        public string CUSTOM_TEXT_5 { get; set; }
        public string CUSTOM_TEXT_6 { get; set; }
        public string CUSTOM_TEXT_7 { get; set; }
        public string CUSTOM_TEXT_8 { get; set; }
        public string CUSTOM_TEXT_9 { get; set; }
        public string CUSTOM_TEXT_10 { get; set; }
        public string CUSTOM_TEXT_11 { get; set; }
        public string CUSTOM_TEXT_12 { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string ADDRESS_3 { get; set; }
        public string ADDRESS_4 { get; set; }
        public string ADDRESS_5 { get; set; }
        public string TITLE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string JOB_NUMBER { get; set; }
        public string CODE_TYPE_NUMBER { get; set; }
        public string DRAWING_NUMBER { get; set; }
        public string DOMICILE { get; set; }
        public string SAFETY_CLASS { get; set; }
        public string DESIGN_CODE_LOCATION { get; set; }
        public string DESIGN_CODE_GRID_REFERENCE { get; set; }
        public string DESIGN_CODE_SEISMIC_ZONE_NAME { get; set; }
        public string TERRAIN_CATEGORY { get; set; }
        public string WIND_ZONE { get; set; }
        public string SPANDREL_MATERIALS { get; set; }
        public string GABLE_MATERIALS { get; set; }
        public string LAYOUT_BRACE_SUMMARY { get; set; }
        public string STRONGBACK_SUMMARY { get; set; }
        public string BEAMS_AND_COLUMNS { get; set; }
        public string INFILL { get; set; }
        public string INFILL_DETAILED { get; set; }
        public string SCABS { get; set; }
        public string FRAME_LABELS_SUMMARY { get; set; }
        public string METALWORK_SUMMARY { get; set; }
        public string METALWORK_SUMMARY_WITH_DESCRIPTIONS { get; set; }
        public string METALWORK_SUMMARY_WITH_DESCRIPTION_MINIMAL { get; set; }
        public string METALWORK_SUMMARY_SINGLE_ROW_FIXING { get; set; }
        public string CASSETTE_SUMMARY { get; set; }
        public string DECKING_SUMMARY { get; set; }
        public string SHEETING_SUMMARY { get; set; }
        public string SHEATHING_SUMMARY { get; set; }
        public string REVISION_SUMMARY { get; set; }
        public string WALL_PANEL_DOORS { get; set; }
        public string WALL_PANEL_WINDOWS { get; set; }
        public string WALL_PANEL_LEGEND { get; set; }
        public string WALL_PANELS { get; set; }
        public string SILLS { get; set; }
        public string LOOSE_MEMBERS { get; set; }
        public string SITE_NAILED_PLATES { get; set; }
        public string FASTENERS { get; set; }
        public string SOLE_PLATE_LENGTH_SUMMARY { get; set; }
        public string WALL_PLATE_LENGTH_SUMMARY { get; set; }
        public string SOLE_PLATE_CUTTING_BILL { get; set; }
        public string WALL_PLATE_CUTTING_BILL { get; set; }
        public string STEEL_FRAME { get; set; }
        public double? MATERIAL_TOTAL_TIMBER_VOLUME { get; set; }
        public double? MATERIAL_TOTAL_CIRCULAR_TIMBER_VOLUME { get; set; }
        public double? MATERIAL_TOTAL_LVL_VOLUME { get; set; }
        public double? MATERIAL_TOTAL_GLULAM_VOLUME { get; set; }
        public double? MATERIAL_TOTAL_ALLWOODENITEMS_PRICE { get; set; }
        public double? MATERIAL_TOTAL_TIMBER_PRICE { get; set; }
        public double? MATERIAL_TOTAL_PLATES_PRICE { get; set; }
}